name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish --configuration Release --output ./published

      # ⚡️ Despliegue (opcional) - Cambia estos datos por los de tu servidor
      # - name: Deploy to server (ejemplo de despliegue)
      #   run: |
      #     scp -r ./published usuario@servidor:/path/to/deploy

